apiVersion: v1
kind: Namespace
metadata:
  name: crm
  labels:
    app.kubernetes.io/name: crm
    app.kubernetes.io/part-of: crm-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: crm-monitoring
  labels:
    app.kubernetes.io/name: crm-monitoring
    app.kubernetes.io/part-of: crm-platform
